### ISSUE TITLE
Dates?

### ISSUE THREAD

**Issue by kendonB** [nzherald/nz-covid19-data#1]
I have made a request to MoH (through the feedback button) to add date of likely infection, swab date, and recovery/death date. You may have more away than me though.

**Comment by kendonB** [comment]
In lieu of them adding it, you could add which day a case shows up on the page from now on

**Comment by vizowl** [comment]
Until (or if) they add that the date announced will have to be the best - I just when back through the press releases and assigned a date to each case.

<img width="609" alt="Screen Shot 2020-03-25 at 11 51 05" src="https://user-images.githubusercontent.com/175572/77484419-63163580-6e8f-11ea-8847-f2c7e2a1c6fa.png">

I'll close this now - but if you see the ministry add anymore data hit me up.

**Comment by kendonB** [comment]
@vizowl do you or someone you know have a contact inside MoH you could request this of? I never received a response to my feedback on the webpage
