### ISSUE TITLE
Running count of tests

### ISSUE THREAD

**Issue by PetraOleum** [nzherald/nz-covid19-data#2]
Is that published anywhere? A.B. just said 9780 so far, if I heard correctly

**Comment by vizowl** [comment]
I wish :) As far I it sometimes gets mentioned in the press conferences and sometimes doesn't - sometime I should go and listen to them all again ...

**Comment by PetraOleum** [comment]
Is there an archive of those?

**Comment by vizowl** [comment]
There is - https://www.health.govt.nz/our-work/diseases-and-conditions/covid-19-novel-coronavirus/covid-19-novel-coronavirus-news-and-media-updates

But it is complicated by the language they use - today he said 1421 yesterday he said 'over 900' - I start adding the accurate numbers from today and if someone ;) wants to go back through the releases and look at what the said we could add tests with two columns - a number and an estimate/accurate flag...

**Comment by vizowl** [comment]
Actually I have started it with
```r
testDates <- tribble(
  ~Date, ~Tests, ~`Total Tests`, ~`Test Count`,
  "2020-03-23", NA, 9780-1421-900, "Estimate",
  "2020-03-24", 900, 9780-1421, "Estimate",
  "2020-03-25", 1421, 9780, "Accurate",
  ) %>% mutate(Date=as.Date(Date))
```

I'm not sure whether it would be worth pushing further back - but I do recall numbers were mentioned occasionally so it could be a fun challenge...

**Comment by vizowl** [comment]
The test count summaries don't add up - they are out by a few hundred between yesterday and today - I have left them in my series but I'm not sure if the reported numbers will be reliable enough to do anything with.
