### ISSUE TITLE
South Canterbury?

### ISSUE THREAD

**Issue by tslumley** [nzherald/nz-covid19-data#3]
South Canterbury isn't a Regional Council region (though it's a DHB). Should it be merged with Canterbury in the Region field?

**Comment by vizowl** [comment]
I decided to do regions not DHBs as mostly the Auckland ones are reported as Auckland - but I'm not which case you are thinking about - or are you thinking about the future?

**Comment by tslumley** [comment]
?I'm just thinking that South Canterbury should be merged with Canterbury if you're doing regions


  -thomas


Thomas Lumley
Professor of Biostatistics
University of Auckland
________________________________

**Comment by vizowl** [comment]
Looks like I am no longer doing regions - I am following the Ministry's switch the DHBs....
