### ISSUE TITLE
Automated scraping of MOH and other sites

### ISSUE THREAD

**Issue by simeonmiteff** [nzherald/nz-covid19-data#5]
Hi there!

I have been scraping the MOH, MSD and covid19.govt.nz sites for a few days now and making the data available via a web API in various formats:

https://nzcovid19api.xerra.nz/

You might find the code that does the scraping useful in an offline workflow (the command line tool can output CSV and JSON): https://github.com/simeonmiteff/nzcovid19cases

Some researchers have asked me for reported dates, and I have spent some time manually joining these with the MOH table in this Google Sheet (which pulls the table from the API's CSV feed using the `IMPORTDATA()` function that updates every 30 minutes):

https://docs.google.com/spreadsheets/d/1NJiDg2z7Y79RUkQ-a648fFD_EmziztYLLkQW_FOrLGo/edit#gid=576672848

Please let me know if I can help out in some way.

More generally, I know of at least one initiative to build a sensible data format for MOH to do their reporting, but I don't know if there is anyone on the ministry's end to take this on (especially given that I think they have _bigger problems_ right now).

I also found that the MOH site gets overloaded once a day, and at other times has a nasty caching bug where it alternately serves the latest, and outdated versions of the COVID-19 case page. I've been trying to find out who the tech contact is there (to offer help), but no luck yet. Please let me know if you know someone who can connect me at MOH.

Regards,
Simeon.

**Comment by vizowl** [comment]
Hi - Great work I wish I had seen it before! As you mentioned in #6 things are a bit broken now - but I'll let you know if I find anything out - and feel free to give me a yell if you see something.
