### ISSUE TITLE
New source of individual case information?

### ISSUE THREAD

**Issue by simeonmiteff** [nzherald/nz-covid19-data#6]
I guess you folks have seen that MOH reworked the cases page now to show only case statistics.

Does someone who MOH takes seriously (NZ Herald?) know if they plan to publish individual case information at all?

**Comment by vizowl** [comment]
Yes :(

I will ask - I don't know how far I'll get - they did say in the press conference that details of the ages and gender will be made available - but we'll see.

I have worked around the change for now...
